function net = train_cnn(XECGTrain,XSpO2Train,YTrain)

%TRAIN_CNN Two-branch ECG + SpO2 sequence labeller.
%
% ECG input:
%   50 Hz
%   temporal CNN
%   approximately 10 seconds of ECG receptive field
%   reduced internally to 1 Hz
%
% SpO2 input:
%   1 Hz
%   one scalar per output second
%   kernel size 1 only, so no neighbouring SpO2 values are mixed
%
% Output:
%   one N/A probability pair per second.

%% Class weights from training patients only

labels = vertcat(YTrain{:});

counts = [ ...
    sum(labels == 'N'), ...
    sum(labels == 'A') ...
    ];

assert( ...
    all(counts > 0), ...
    'Both N and A must occur in the training patients.');

classWeights = ...
    (sum(counts)./counts).^0.75;

classWeights = ...
    classWeights / mean(classWeights);

classWeights = single(classWeights);

fprintf('Training seconds: %d\n', numel(labels));
fprintf('Training N: %d\n', counts(1));
fprintf('Training A: %d\n', counts(2));

fprintf( ...
    'Class weights [N A]: [%.3f %.3f]\n', ...
    classWeights(1), ...
    classWeights(2));

%% ECG branch
%
% Temporal reduction:
%
% 50 Hz
%  -> /5 = 10 Hz
%  -> /5 = 2 Hz
%  -> /2 = 1 Hz
%
% The final 7-sample convolution happens AFTER reduction to 1 Hz.
% This gives roughly a 10-second ECG receptive field.

ecgLayers = [

    sequenceInputLayer( ...
        1, ...
        Normalization="none", ...
        MinLength=50, ...
        Name="ecg")

    convolution1dLayer( ...
        9,16, ...
        Padding="same", ...
        Name="ecg_conv1")

    batchNormalizationLayer( ...
        Name="ecg_bn1")

    reluLayer( ...
        Name="ecg_relu1")

    maxPooling1dLayer( ...
        5, ...
        Stride=5, ...
        Name="ecg_pool1")

    convolution1dLayer( ...
        7,32, ...
        Padding="same", ...
        Name="ecg_conv2")

    batchNormalizationLayer( ...
        Name="ecg_bn2")

    reluLayer( ...
        Name="ecg_relu2")

    maxPooling1dLayer( ...
        5, ...
        Stride=5, ...
        Name="ecg_pool2")

    convolution1dLayer( ...
        5,64, ...
        Padding="same", ...
        Name="ecg_conv3")

    batchNormalizationLayer( ...
        Name="ecg_bn3")

    reluLayer( ...
        Name="ecg_relu3")

    maxPooling1dLayer( ...
        2, ...
        Stride=2, ...
        Name="ecg_pool3")

    convolution1dLayer( ...
        7,64, ...
        Padding="same", ...
        Name="ecg_temporal")

    batchNormalizationLayer( ...
        Name="ecg_bn4")

    reluLayer( ...
        Name="ecg_relu4")
    ];

%% SpO2 branch
%
% SpO2 already exists at 1 Hz.
%
% Kernel size 1 means each output second only receives
% the SpO2 value belonging to that same second.

spo2Layers = [

    sequenceInputLayer( ...
        1, ...
        Normalization="none", ...
        MinLength=1, ...
        Name="spo2")

    convolution1dLayer( ...
        1,8, ...
        Padding="same", ...
        Name="spo2_current")

    reluLayer( ...
        Name="spo2_relu")
    ];

%% Classification head
%
% ECG and SpO2 now have the SAME 1-Hz time dimension.
%
% Concatenation is across channels, not time.

headLayers = [

    concatenationLayer( ...
        1,2, ...
        Name="concat")

    fullyConnectedLayer( ...
        64, ...
        Name="fc1")

    reluLayer( ...
        Name="head_relu")

    dropoutLayer( ...
        0.2, ...
        Name="dropout")

    fullyConnectedLayer( ...
        2, ...
        Name="fc_output")

    softmaxLayer( ...
        Name="softmax")
    ];

%% Assemble two-input network

lgraph = layerGraph();

lgraph = addLayers(lgraph,ecgLayers);
lgraph = addLayers(lgraph,spo2Layers);
lgraph = addLayers(lgraph,headLayers);

lgraph = connectLayers( ...
    lgraph, ...
    "ecg_relu4", ...
    "concat/in1");

lgraph = connectLayers( ...
    lgraph, ...
    "spo2_relu", ...
    "concat/in2");

testNet = dlnetwork(lgraph);

%% Shape checks

% One second:
%
% ECG = 50 samples
% SpO2 = one scalar
% Output = one prediction.

testECG = ...
    dlarray(zeros(1,50,'single'),'CT');

testSpO2 = ...
    dlarray(zeros(1,1,'single'),'CT');

shortOutput = predict( ...
    testNet, ...
    testECG, ...
    testSpO2);

assert( ...
    size(shortOutput,1) == 2 && ...
    size(shortOutput,2) == 1, ...
    '50 ECG samples + 1 SpO2 value must produce 1 prediction.');

% Two seconds.

testECG = ...
    dlarray(zeros(1,100,'single'),'CT');

testSpO2 = ...
    dlarray(zeros(1,2,'single'),'CT');

twoSecondOutput = predict( ...
    testNet, ...
    testECG, ...
    testSpO2);

assert( ...
    size(twoSecondOutput,1) == 2 && ...
    size(twoSecondOutput,2) == 2, ...
    '100 ECG samples + 2 SpO2 values must produce 2 predictions.');

% Full 60-second block.

testECG = ...
    dlarray(zeros(1,3000,'single'),'CT');

testSpO2 = ...
    dlarray(zeros(1,60,'single'),'CT');

fullOutput = predict( ...
    testNet, ...
    testECG, ...
    testSpO2);

assert( ...
    size(fullOutput,1) == 2 && ...
    size(fullOutput,2) == 60, ...
    '60 seconds must produce 60 predictions.');

fprintf('CNN shape checks passed:\n');
fprintf('  50 ECG samples + 1 SpO2 value -> 1 prediction\n');
fprintf('  100 ECG samples + 2 SpO2 values -> 2 predictions\n');
fprintf('  3000 ECG samples + 60 SpO2 values -> 60 predictions\n');

%% Training datastore
%
% trainnet requires a combined datastore for a network with
% multiple inputs.
%
% Each observation provides:
%
%   ECG sequence
%   SpO2 sequence
%   target sequence

dsECG = arrayDatastore( ...
    XECGTrain, ...
    OutputType="same");

dsSpO2 = arrayDatastore( ...
    XSpO2Train, ...
    OutputType="same");

dsY = arrayDatastore( ...
    YTrain, ...
    OutputType="same");

dsTrain = combine( ...
    dsECG, ...
    dsSpO2, ...
    dsY);

%% Weighted cross-entropy

lossFcn = @(scores,targets) 2 * crossentropy( ...
    scores, ...
    targets, ...
    classWeights, ...
    WeightsFormat="UC", ...
    ClassificationMode="single-label", ...
    NormalizationFactor="all-elements");

%% Training

options = trainingOptions( ...
    "adam", ...
    MaxEpochs=10, ...
    MiniBatchSize=32, ...
    Shuffle="every-epoch", ...
    ExecutionEnvironment="auto", ...
    InputDataFormats=["TCB","TCB"], ...
    TargetDataFormats="TCB", ...
    Verbose=true, ...
    Plots="none");

net = trainnet( ...
    dsTrain, ...
    testNet, ...
    lossFcn, ...
    options);

end